### ISSUE TITLE
Longterm Fetch and Place startup sometimes hanging

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/longterm_fetch_and_place#24]
When starting the main simulation environment with

``` bash
$ roslaunch ltfnp_executive ltfnp_simulation.launch
```

Every third time or so the startup sequence hangs after this output:

``` bash
[ INFO] [1469523624.070525619, 5.697000000]: Initializing OMPL interface using ROS parameters
[ INFO] [1469523624.103960070, 5.697000000]: Using planning interface 'OMPL'
[ INFO] [1469523624.183989909, 5.697000000]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1469523624.184482406, 5.697000000]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1469523624.184863773, 5.697000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1469523624.185280942, 5.697000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1469523624.185672828, 5.697000000]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1469523624.186090230, 5.697000000]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1469523624.186132119, 5.697000000]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1469523624.186196989, 5.697000000]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1469523624.186218372, 5.697000000]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1469523624.186247095, 5.697000000]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1469523624.186278816, 5.697000000]: Using planning request adapter 'Fix Start State Path Constraints'
```

What gets started fine so far is
- `roscore`
- KnowRob / `json_prolog`
- `gzserver`
- Several PR2 related drivers, including spawning the PR2 (so `gzserver` is actually there)

It hangs indefinitely. What doesn't come up completely is MoveIt!. It seems some part of its starting sequence is waiting for some other component. When I `CTRL-C` from there, I see additional output:

``` bash
^C[nav_pcontroller-36] killing on exit
[move_group-35] killing on exit
[static_world_frame-34] killing on exit
[kitchen_state_publisher-33] killing on exit
[spawn_kitchen-32] killing on exit
[kitchen_joint_state_publisher-31] killing on exit
[room_link_broadcaster-30] killing on exit
[torso_controller/position_joint_action_node-29] killing on exit
[head_traj_controller/point_head_action-28] killing on exit
[l_gripper_controller/gripper_action_node-27] killing on exit
[r_gripper_controller/gripper_action_node-26] killing on exit
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/gazebo_ros/spawn_model", line 293, in <module>
    sm.callSpawnService()
  File "/opt/ros/indigo/lib/gazebo_ros/spawn_model", line 259, in callSpawnService
    initial_pose, self.reference_frame, self.gazebo_namespace)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 32, in spawn_urdf_model_client
    resp = spawn_urdf_model(model_name, model_xml, robot_namespace, initial_pose, reference_frame)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
[default_controllers_spawner-25] killing on exit
[camera_synchronizer_node-24] killing on exit
[tf2_buffer_server-23] killing on exit
[tilt_hokuyo_node-22] killing on exit
[base_hokuyo_node-21] killing on exit
[robot_pose_ekf-20] killing on exit
[pr2_dashboard_aggregator-19] killing on exit
[diag_agg-18] killing on exit
[l_forearm_cam/image_proc-17] killing on exit
Loading 'move_group/MoveGroupCartesianPathService'...
[r_forearm_cam/image_proc-16] killing on exit
[right_camera_info_relay-15] killing on exit
[left_camera_info_relay-14] killing on exit
[right_image_raw_relay-13] killing on exit
[left_image_raw_relay-12] killing on exit
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
[narrow_stereo_textured/narrow_stereo_textured_proc-11] killing on exit
[narrow_stereo/narrow_stereo_proc-10] killing on exit
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...

All is well! Everyone is happy! You can start planning now!

[wide_stereo/wide_stereo_proc-9] killing on exit
[fake_joint_calibration-8] killing on exit
[pr2_mechanism_diagnostics-7] killing on exit
[robot_state_publisher-6] killing on exit
[gazebo_gui-4] killing on exit
[map_server-1] killing on exit
[gazebo-3] killing on exit
[json_prolog-2] killing on exit
[default_controllers_spawner-25] escalating to SIGTERM
[WARN] [WallTime: 1469524352.918540] [5.697000] Spawner couldn't reach pr2_controller_manager to take down controllers.
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 161, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 139, in main
    resp = load_controller(name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
[gazebo-3] escalating to SIGTERM
shutting down processing monitor...
... shutting down processing monitor complete
done
```

So MoveIt! comes up after that, right before being quit due to `CTRL-C` killing `roslaunch`. The interrupted Python script clues towards ...:

``` bash
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/gazebo_ros/spawn_model", line 293, in <module>
    sm.callSpawnService()
  File "/opt/ros/indigo/lib/gazebo_ros/spawn_model", line 259, in callSpawnService
    initial_pose, self.reference_frame, self.gazebo_namespace)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 32, in spawn_urdf_model_client
    resp = spawn_urdf_model(model_name, model_xml, robot_namespace, initial_pose, reference_frame)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
```

So something is not spawned properly, or the spawn process isn't finishing up. This would fit the fact that the kitchen spawn process is being started, e.g. `process[spawn_kitchen-32]: started with pid [20024]`, but only finishes after `CTRL-C`: `[spawn_kitchen-32] killing on exit`.

This strongly looks like a race condition between the Gazebo spawning service and the kitchen spawning call; but the PR2 gets spawned just fine right before. Its process even quits gracefully: `[spawn_pr2_model-5] process has finished cleanly`.

The full output is in [this pastebin](http://pastebin.com/tbVWUjnE).

@bbrieber is there anything special about spawning the kitchen?

**Comment by gaya-** [comment]
(As a side note, @fairlight1337 why don't you want to use a newer version of Gazebo? It solves a lot of bugs.)

**Comment by fairlight1337** [comment]
@gaya- because this version comes with the debs. Compiling and packaging a newer version of Gazebo, plus making sure that the ROS plugin works properly, is beyond my current time budget.

Also, how do you know this gets resolved with the newer Gazebo version? I'll comment in a minute about new insights, suggesting that this in fact isn't necessarily related to Gazebo itself.

**Comment by fairlight1337** [comment]
Digging a bit into the files that get called showed that `sm.callSpawnService()` is actually the regular `spawn_model` service of Gazebo, which is just doing its job by sitting there and waiting for other nodes to communicate new spawn requests. I'm not sure yet why this is, but apparently the second Python notice on interruption suggests that the PR2 controllers are not finishing up loading:

``` bash
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 161, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 139, in main
    resp = load_controller(name)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
```

I'll keep looking.

**Comment by fairlight1337** [comment]
The PR2 controllers are apparently innocent. [Here](http://pastebin.com/hQXJv5YQ) is a log of a successful startup. It yields the same errors. I'll compare the two now.

**Comment by fairlight1337** [comment]
Intermediate clue: The line that _isn't_ reached when the startup isn't working is this one:

``` bash
[ INFO] [1469525376.137547487]: Trajectory execution is managing controllers
```

So this might be related to the controllers after all, but definitely something in MoveIt! that is waiting indefinitely.

**Comment by fairlight1337** [comment]
Building on the last insight, I changed the [`moveit_manage_controllers`](https://github.com/code-iai/longterm_fetch_and_place/blob/master/pr2_moveit_node/launch/move_group.launch#L34) setting in the `move_group.launch` file to `false`:

``` xml
<!-- Trajectory Execution Functionality -->
<include ns="move_group" file="$(find pr2_moveit_node)/launch/trajectory_execution.launch.xml" if="$(arg allow_trajectory_execution)">
  <arg name="moveit_manage_controllers" value="false" />
  [...]
</include>
```

So far this seems to have done the trick. Ten startups without indefinite waiting times; so this was related to the internal MoveIt! controllers that somehow are affected by a race condition from the numerous nodes that get started on the fetch and place scenario.

While I can't point to the exact offender right now, this fixes the issue for me. I will address it in a pull request just now.
